### ISSUE TITLE
createWriteStream is uploading my images with smaller size or 0kb

### ISSUE THREAD

**Issue by melcarniel** [perry-mitchell/webdav-client#271] opened 2021-08-30 20:45 UTC
I am using webdav-client to upload images to webdav, I am downloading the images and saving in a root directory, then uploading to webdav, maybe I am implementing wrong. Can someone help?

```
const pathString = Path.join(__dirname, 'images', `${name}.jpg`);

// save the image 
await this.serviceSocialMedia.downloadImages(url, writer);
 const readStream = Fs.createReadStream(pathString);
    const writeStream = await client.createWriteStream(`/product_images/${name}.jpg`);
    readStream.pipe(writeStream);

    endOfStream(writeStream, err => {
	    if (err) {
		    console.error(err);
		  return;
	  }
	  console.log("Done +++");
    });
```

**Comment by perry-mitchell** [comment] 2021-09-16 07:56
This is a dupe of #181

**Closed by perry-mitchell** 2021-09-16 07:56 UTC
