### ISSUE TITLE
Can't write from stream

### ISSUE THREAD

**Issue by armpogart** [perry-mitchell/webdav-client#173] opened 2019-08-02 20:32 UTC
I'll try to describe the issue as detailed as possible as it would be impossible to provide you DAV access to test yourself.

So I'm using your client to connect to [BigCommerce](https://bigcommerce.com) WebDav server access. I use your module in [electronjs](https://electronjs.org) application and as BigCommerce CORS doesn't allow requests from localhost (both API and DAV), I use also proxy to add CORS to the requests (self hosted https://cors-anywhere.herokuapp.com).

When I try to `createWriteStream` to write file to dav, only a 15B is written (I've checked in Cyberduck client) so the file is broken and I see one 401 Unauthorized request in network tab.
![image](https://user-images.githubusercontent.com/785768/62396405-315d0100-b584-11e9-9fa5-ffdee7af1b9d.png)
In the image above you can see 4 requests with the name of the file (dsc_9913.jpg), these all are just for one `createWriteStream`, something like:
````
fs.createReadStream('dsc_9913.jpg').pipe(
    client.createWriteStream(`/dav/product_images/import/dsc_9913.jpg`, {
        overwrite: true,
    }),
);
````
2 of the requests with status 200 are `OPTIONS` requests. 2 others are `PUT` requests. I'm not sure why there are 2 of each there. So the first `PUT` request fails, but second one is ok, but creates broken file (Authorization is correct, as 2nd one is ok). Below you can also see all 4 requests in their order (they have a little bit different headers somehow):
![image](https://user-images.githubusercontent.com/785768/62396830-353d5300-b585-11e9-82d0-02649a0eea5c.png)
![image](https://user-images.githubusercontent.com/785768/62396944-76356780-b585-11e9-917a-4eed4d905260.png)
![image](https://user-images.githubusercontent.com/785768/62396976-9402cc80-b585-11e9-863d-faa5f9164277.png)
![image](https://user-images.githubusercontent.com/785768/62397071-d7f5d180-b585-11e9-906e-965367307f90.png)

I'm almost sure that proxy is ok, as it is also used with BigCommerce API (Restful) and is doing its' job.
Not sure whether it's bug or something is wrong with my setup, but will appreciate any help.

P.S. If you really need to reproduce the issue, you can register for trial account on bigcommerce website and I can provide you the source code and setup a proxy for you to try the same setup.

**Comment by perry-mitchell** [comment] 2019-08-03 09:53
Hello! That’s a weird issue. Thanks for the clear write up, I’ll see if I can help figure out what’s going on. All the requests look wrong, IMO. The options are fine but there should only be one of each like you stated. The PUT should be sending an octet stream, not form encoded.. so that’s a larger concern.

I see you’re using Digest auth, which is super cool, but it’s brand new so I wouldn’t rule out a bug there. Perhaps it’d be best if you send me some code and I register for a trial account. 

Have you tried doing this from Nodejs without the proxy or browser? That’d tell a lot with regards to where the issue is.

**Comment by armpogart** [comment] 2019-08-24 16:34
@perry-mitchell 
I'm using Digest auth, as it simply doesn't work without it. I get 401 Unauthorized. Not sure why, as I don't see anything mentioned about Digest auth in BigCommerce webdav docs (https://support.bigcommerce.com/s/article/File-Access-WebDAV).
I have also tested `getDirectoryContents` and I get similar results in terms of requests, but I get the response with file stats. So it is at least working, but I see duplicate requests there, one of which is again 401 Unauthorized.

I have prepared full reproduction repo for you (https://github.com/armpogart/webdav-bugrepo). You just need to clone it, register for trial at https://www.bigcommerce.com/essentials/, then go to your bigcommerce dashboard **Server Settings** -> **File Access (WebDav)** to get the credentials, set them at `AppModule` (https://github.com/armpogart/webdav-bugrepo/blob/master/src/app/app.module.ts), you will see the example config there with webdav url after proxy.
After that just do `npm install` and `npm start`, electron application will start and immediately open DevTools for debugging. The code that is running is at `AppComponent`s `ngOnInit` method` (https://github.com/armpogart/webdav-bugrepo/blob/master/src/app/app.component.ts).

I will greatly appreciate if you find time to help me debug the problem and find out why this great library isn't working for me. I have done maximum to get you started very quick. Thanks in advance.

P.S. I haven't tried to try from NodeJS directly as I don't have an appropriate environment (I mean not local NodeJS environment to exclude also proxy, though I doubt the problem is proxy as it simply proxies all requests and the proxy implementation is also open-source - [cors-anywhere](https://github.com/Rob--W/cors-anywhere)). I see that doing it will help us isolate the problem more to understand whether it's the problem with BigCommerce webdav server incompatibility or something with using it from browser by wrapping it in electron-angular app or maybe proxy.

**Comment by perry-mitchell** [comment] 2019-09-05 18:48
Hi @armpogart, apologies for not coming back sooner.

> So it is at least working, but I see duplicate requests there, one of which is again 401 Unauthorized.

Duplicate requests can be a symptom of CORS fetches (OPTIONS + real request). 401 may be an issue with the service in such a case. I'm obviously only speculating as I haven't tried with BigCommerce.

I also don't have the time right now to debug this further, but for now I feel that it's an isolated issue with their platform.

If you get time to try from NodeJS that'll definitely help shed some light on the issue. If I get time I'll have a crack, but I've got several ongoing high priority projects right now.

**Comment by perry-mitchell** [comment] 2019-10-12 12:27
Any luck trying this with Node rather than in the browser? It can be done with a relatively simple node script which would quickly confirm whether this is just a browser issue with the service.

**Comment by armpogart** [comment] 2019-10-20 12:37
@perry-mitchell I will have a spare time coming week and will try first with node directly and also I will try again in browser without proxy this time, I've found out how I can disable web security for Electron (chromium), so to bypass the issue with localhost and CORS.

I will let you know what worked and what not soon.
Thanks again.

**Comment by perry-mitchell** [comment] 2021-02-01 20:40
Closing as this is very out of date. Let's create a new issue if the problem persists.

**Closed by perry-mitchell** 2021-02-01 20:40 UTC
