### ISSUE TITLE
onUploadProgress is not triggering.

### ISSUE THREAD

**Issue by cihanbey211** [perry-mitchell/webdav-client#319] opened 2022-09-07 13:22 UTC
Hi everyone; Firstly thank you for this module. I need onUploadProgress trigger for big files, but not triggering. I need help yours about issue.

`function uploadFile(client) {
    console.log('Start');
    const file = fs.createReadStream("./video.mp4");
    client.putFileContents("/video.mp4", file, {
        overwrite: false,
        onUploadProgress: progress => {
  	     console.log(progress);
        }
    });
}`

**Comment by perry-mitchell** [comment] 2022-09-08 17:40
Hi @cihanbey211 - just confirming, are you using this in the browser or node?

**Comment by cihanbey211** [comment] 2022-09-09 10:55
> Hi @cihanbey211 - just confirming, are you using this in the browser or node?

Hi sir, i couldn't get views on either side, is there a way you suggest?

**Comment by mtdvlpr** [comment] 2022-11-27 09:47
I also have this issue. I'm using it in the browser, but it only triggers once when the upload is done.

**Comment by perry-mitchell** [comment] 2022-11-27 19:32
I'm not sure what could be happening here, though to be honest I've not really used those functions in my own projects. From what I've seen they are incredibly unstable and work for some while never for others. That and such methods are _not_ available on the new Fetch standard.

It's sad to say but these methods (upload/download progress) will disappear on v5 of this library, when I switch away from Axios (for Fetch). Progress will be possible to calculate by viewing the _stream_ position when streaming files to or from the remote source, but not via normal options. I don't want to implement these myself (as they'd be problematic, just bloat for most people and only available reliably on the Node side).

I'll leave this issue open if someone's interested in fixing this for V4 (not sure how that'd be possible, as we simply pass these properties on to Axios, so any bug is most likely there), but I'll close it when V5 is stable.

**Comment by mtdvlpr** [comment] 2022-11-27 21:34
Okay, thanks for the explanation!

**Comment by perry-mitchell** [comment] 2022-11-30 19:58
Confirmed with the latest set of changes - upload/download progress will be **dropped**. Using streams + middleware to measure progress is the best way, especially because streams are better than buffering an entire file beforehand (usually required to be able to know upload size, and therefore progress (total/percentage)).

I'll try to add an example for this at some point.

**Closed by perry-mitchell** 2022-11-30 19:58 UTC
