### ISSUE TITLE
Anyway to ignore SSL certificate validation

### ISSUE THREAD

**Issue by gsejourne** [perry-mitchell/webdav-client#39] opened 2017-06-16 13:10 UTC
Just like the -k option in Curl, is there any way to perform so-called "insecure" SSL connections  to the Webdav server ?
I looked at the client init script, like so:
`var client = createClient(
    "https://webdav-server.org/remote.php/webdav",
    "username",
    "password"
);
`
and an "IgnoreCertificateErrors" option would be great.
Is there any way I can bypass this ?

**Comment by perry-mitchell** [comment] 2017-06-16 18:48
Thanks for posting @gsejourne.

We use [this library](https://github.com/bitinn/node-fetch) to do remote requests.. so if something is blocking insecure HTTPS requests it would be that. I currently don't have time to setup a HTTPS server to test this, however.

Would you mind if I ask why you would want such a feature? Certs are easily created for free these days so I don't see any reason to use HTTPS without a verifiable certificate.

**Comment by gsejourne** [comment] 2017-06-19 06:54
Well, that's counting without internal IT maelstrom, and the fact that I need to hit the internal IP address from within our network, as the DNS record points to the external one.

**Comment by perry-mitchell** [comment] 2017-06-20 05:15
That's a fair use case, but why not use a FQDN for the internal network? If the system is **myserver.com** externally and **myserver** internally, wouldn't that be better? You could then test with a self-signed certificate which might work.

Otherwise, on this issue, I don't have the resources currently to test any modifications, so help would be very welcome. What is needed is a way to confirm that this breaks on HTTPS without a cert, and if there even is any way to bypass that protection.

**Comment by perry-mitchell** [comment] 2017-07-25 06:40
As far as I see it currently, I don't feel that this is the responsibility of this library. This is solely a networking issue and would be better handled, imo, by enabling HTTP internally with some hostname to make it more easily accessible. Bypassing SSL security restrictions is perhaps not something I'd want to add a feature for.

I am open to discussion surrounding SSL handling at a low level within this library, but because it can use a variety of request engines it makes it a bit difficult to narrow down what might be the cause of the issue you're seeing. I'll close this for now.

**Closed by perry-mitchell** 2017-07-25 06:40 UTC
