### ISSUE TITLE
Issue with hot-patcher at building a project 

### ISSUE THREAD

**Issue by javilag** [perry-mitchell/webdav-client#314] opened 2022-08-18 19:57 UTC
i'm trying to make a build with webdav but i'm finding the next error 
```
"node_modules/webdav/dist/node/compat/patcher.d.ts:1:24 - error TS7016: Could not find a declaration file for module 'hot-patcher'. '.../node_modules/webdav/node_modules/hot-patcher/source/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/hot-patcher` if it exists or add a new declaration (.d.ts) file containing `declare module 'hot-patcher';`


1 import HotPatcher from "hot-patcher";
```
i'm using the strict mode in false and this error still happen.

**Comment by perry-mitchell** [comment] 2022-08-21 17:23
Hi @javilag - I'm not sure what the issue is here, but it looks as though your configuration is trying to validate types in `node_modules`. I don't personally follow such a system, and hot patcher is not _yet_ typescript. I plan to update it eventually but haven't yet had time.

It's best that you just ignore this for now by preventing Typescript from validating types in node modules. [Try `"skipLibCheck": true` in `tsconfig.json`](https://www.typescriptlang.org/tsconfig/skipLibCheck.html).

I'll close this as it's not an issue I plan to address as WebDAV works just fine.

**Closed by perry-mitchell** 2022-08-21 17:23 UTC

**Comment by perry-mitchell** [comment] 2022-08-21 17:33
This should be fixed by this incoming [PR](https://github.com/perry-mitchell/webdav-client/pull/315).
